version: '3'
services:
  neo4j:
    image: ${NEO4J_IMAGE_URL}
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_server_default__listen__address: 0.0.0.0
      NEO4J_server_bolt_advertised__address: :7687
      NEO4J_dbms_databases_seed__from__uri__providers: URLConnectionSeedProvider,S3SeedProvider
      NEO4JLABS_PLUGINS: '["apoc"]'
    volumes:
      - "./seeds:/seeds"