version: '3.7'
services:
    neo4j:
        hostname: neo4j
        image: neo4j:${NEO4J_VERSION}
        environment:
            - NEO4J_dbms_mode=SINGLE
            - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
            - NEO4J_dbms_default__listen__address=0.0.0.0
            - NEO4J_dbms_default__advertised__address=localhost
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_AUTH=neo4j/password
            - NEO4J_dbms_routing_listen__address=0.0.0.0:7688
        ports:
            - 7474:7474
            - 7473:7473
            - 7687:7687