version: '3'
services:
  neo4j:
    image: neo4j:${NEO4J_VERSION}
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_server_metrics_enabled: true
      NEO4J_server_metrics_prometheus_enabled: true
      NEO4J_server_metrics_prometheus_endpoint: 0.0.0.0:2004
      NEO4J_server_metrics_csv_enabled: false
  prometheus:
    image: prom/prometheus:v2.43.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
  grafana:
    image: grafana/grafana:8.5.22
    ports:
      - 3000:3000
    # volumes:
    #   - ./grafana/provisioning:/etc/grafana/provisioning/
    depends_on:
      - prometheus