version: '3.7'
services:
    core1:
        hostname: core1
        image: neo4j:${NEO4J_VERSION}
        environment:
            - NEO4J_dbms_mode=SINGLE
            - NEO4J_dbms_clustering_enable=TRUE
            - NEO4J_dbms_connector_bolt_advertised__address=localhost:17687
            - NEO4J_dbms_default__listen__address=0.0.0.0
            - NEO4J_dbms_default__advertised__address=core1
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_AUTH=neo4j/password
            - NEO4J_dbms_routing_enabled=true
            - NEO4J_dbms_routing_default__router=SERVER
            - NEO4J_dbms_routing_listen__address=0.0.0.0:7688
        ports:
            - 17474:7474
            - 17473:7473
            - 17687:7687
    rr1:
        hostname: rr1
        image: neo4j:${NEO4J_VERSION}
        environment:
            - NEO4J_dbms_mode=READ_REPLICA
            - NEO4J_dbms_connector_bolt_advertised__address=localhost:57687
            - NEO4J_dbms_default__advertised__address=rr1
            - NEO4J_causal__clustering_initial__discovery__members=core1:5000
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_AUTH=neo4j/password
            - NEO4J_dbms_routing_enabled=true
            - NEO4J_dbms_routing_default__router=SERVER
            - NEO4J_dbms_routing_listen__address=0.0.0.0:7688
            - NEO4JLABS_PLUGINS=["apoc","graph-data-science"]
        ports:
            - 57474:7474
            - 57473:7473
            - 57687:7687
