version: '3'
services:
  neo4j:
    image: neo4j:5.4.0-enterprise
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - "./server-logs.xml:/var/lib/neo4j/conf/server-logs.xml"
    environment:
      - NEO4J_DEBUG=true
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes