version: '3.7'
services:
    core1:
        hostname: core1
        image: neo4j:${NEO4J_VERSION}
        environment:
            - NEO4J_dbms_mode=SINGLE
            - NEO4J_dbms_clustering_enable=TRUE
            - NEO4J_dbms_connector_bolt_advertised__address=localhost:17687
            - NEO4J_dbms_default__listen__address=0.0.0.0
            - NEO4J_dbms_default__advertised__address=core1
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_AUTH=neo4j/password
            - NEO4J_dbms_routing_enabled=true
            - NEO4J_dbms_routing_default__router=SERVER
            - NEO4J_dbms_routing_listen__address=0.0.0.0:7688
            - NEO4J_metrics_enabled=true
            - NEO4J_metrics_namespaces_enabled=true
            - NEO4J_metrics_prometheus_enabled=true
            - NEO4J_metrics_prometheus_endpoint=0.0.0.0:2004
        ports:
            - 17474:7474
            - 17473:7473
            - 17687:7687
            - 2004:2004
    node-exporter:
      image: prom/node-exporter:v0.18.1
      hostname: node-exporter
      container_name: node-exporter
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
      command:
        - '--path.procfs=/host/proc'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.ignored-mount-points'
        - '^(aufs|proc|nsfs|shm|cgroup|tmpfs|binfmt_misc|debugfs|devpts|fusectl|hugetlbfs|fuse.lxcfs|mqueue|pstore|securityfs|sysfs|autofs|devtmpfs|configfs)'
    prometheus:
      image: prom/prometheus
      hostname: prometheus
      container_name: prometheus
      ports:
        - 9090:9090
      volumes:
        - ./prometheus/:/etc/prometheus/
      depends_on:
        - node-exporter
        - alertmanager
    grafana:
      image: grafana/grafana:7.4.1
      hostname: grafana
      container_name: grafana
      environment:
        GF_INSTALL_PLUGINS: grafana-piechart-panel
      ports:
        - 3000:3000
      # volumes:
      #   - ./grafana/provisioning:/etc/grafana/provisioning/
      depends_on:
        - prometheus