version: '3.7'
services:
    core1:
        hostname: core1
        image: neo4j:${NEO4J_VERSION}
        environment:
            - NEO4J_dbms_mode=SINGLE
            - NEO4J_dbms_connector_bolt_advertised__address=localhost:17687
            - NEO4J_dbms_default__listen__address=0.0.0.0
            - NEO4J_dbms_default__advertised__address=core1
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_AUTH=neo4j/password
            - NEO4J_dbms_routing_enabled=true
            - NEO4J_dbms_routing_default__router=SERVER
            - NEO4J_dbms_routing_listen__address=0.0.0.0:7688
            - NEO4J_fabric_database_name=matrix
        ports:
            - 17474:7474
            - 17473:7473
            - 17687:7687
    neo4j-config-cli:
        image: graphaware/neo4j-config-cli:1.3.0
        environment:
            - NEO4J_USER=neo4j
            - NEO4J_PASSWORD=password
            - NEO4J_URI=bolt://core1:7687
            - IMPORT_PATH=/config
        volumes:
            - "./config:/config"
