version: '3.7'
services:
    core1:
        hostname: core1
        build: .
        cap_add:
            - NET_ADMIN
        environment:
            - NEO4J_dbms_mode=core
            - NEO4J_dbms_connector_bolt_advertised__address=localhost:17687
            - NEO4J_dbms_default__listen__address=0.0.0.0
            - NEO4J_dbms_default__advertised__address=core1
            - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=2
            - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=2
            - NEO4J_causal__clustering_initial__discovery__members=core1:5000,core2:5000,core3:5000
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_AUTH=neo4j/password
            - NEO4JLABS_PLUGINS=["apoc-core"]
        ports:
            - 17474:7474
            - 17473:7473
            - 17687:7687
        volumes:
            - "./data/core1/backups:/backups"
    core2:
        hostname: core2
        build: .
        cap_add:
            - NET_ADMIN
        environment:
            - NEO4J_dbms_mode=core
            - NEO4J_dbms_connector_bolt_advertised__address=localhost:27687
            - NEO4J_dbms_default__listen__address=0.0.0.0
            - NEO4J_dbms_default__advertised__address=core2
            - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=2
            - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=2
            - NEO4J_causal__clustering_initial__discovery__members=core1:5000,core2:5000,core3:5000
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_AUTH=neo4j/password
            - NEO4JLABS_PLUGINS=["apoc-core"]
        ports:
            - 27474:7474
            - 27473:7473
            - 27687:7687
        volumes:
            - "./data/core2/backups:/backups"
    core3:
        hostname: core3
        build: .
        cap_add:
            - NET_ADMIN
        environment:
            - NEO4J_dbms_mode=core
            - NEO4J_dbms_connector_bolt_advertised__address=localhost:37687
            - NEO4J_dbms_default__listen__address=0.0.0.0
            - NEO4J_dbms_default__advertised__address=core3
            - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=2
            - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=2
            - NEO4J_causal__clustering_initial__discovery__members=core1:5000,core2:5000,core3:5000
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_AUTH=neo4j/password
            - NEO4JLABS_PLUGINS=["apoc-core"]
        ports:
            - 37474:7474
            - 37473:7473
            - 37687:7687
        volumes:
            - "./data/core3/backups:/backups"
