version: '3'

# common environment settings that can be reused across all members
x-neo4j-config-common: &neo4j-config-common
  NEO4J_AUTH: neo4j/password
  # NEO4J_server_cluster_system__database__mode: PRIMARY
  NEO4J_initial_server_mode__constraint: NONE
  NEO4J_initial_dbms_default__primaries__count: 1
  NEO4J_initial_dbms_default__secondaries__count: 1
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NEO4J_dbms_cluster_discovery_endpoints: primary1:5000,primary2:5000,primary3:5000
  NEO4J_server_default__listen__address: 0.0.0.0
  NEO4J_server_bolt_advertised__address: :7687
  NEO4J_dbms_databases_seed__from__uri__providers: URLConnectionSeedProvider,S3SeedProvider
  NEO4J_dbms_routing_enabled: true
  NEO4J_dbms_routing_default__router: SERVER
  NEO4J_server_routing_listen__address: 0.0.0.0:7688
  NEO4J_server_routing_advertised__address: :7688
  NEO4J_server_discovery_listen__address: :5000
  NEO4J_server_cluster_listen__address: :6000
  NEO4J_server_cluster_raft_listen__address: :7000

networks:
  lan:

services:
  primary1:
    image: ${NEO4J_IMAGE_URL}
    ports:
      - 17474:7474
      - 17473:7473
      - 16362:6362
      - 17687:7687
    environment:
      <<: *neo4j-config-common
      NEO4J_server_default__advertised__address: primary1
      NEO4J_server_discovery_advertised__address: primary1:5000
      NEO4J_server_cluster_advertised__address: primary1:6000
      NEO4J_server_cluster_raft_advertised__address: primary1:7000
      NEO4J_initial_server_denied__databases: prod1,prod2
    networks:
      - lan
    volumes:
      - "./seeds:/seeds"
      
  primary2:
    image: ${NEO4J_IMAGE_URL}
    ports:
      - 27474:7474
      - 27473:7473
      - 26362:6362
      - 27687:7687
    environment:
      <<: *neo4j-config-common
      NEO4J_server_default__advertised__address: primary2
      NEO4J_server_discovery_advertised__address: primary2:5000
      NEO4J_server_cluster_advertised__address: primary2:6000
      NEO4J_server_cluster_raft_advertised__address: primary2:7000
      NEO4J_initial_server_denied__databases: prod1,prod2
    networks:
      - lan
    volumes:
      - "./seeds:/seeds"

  primary3:
    image: ${NEO4J_IMAGE_URL}
    ports:
      - 37474:7474
      - 37473:7473
      - 36362:6362
      - 37687:7687
    environment:
      <<: *neo4j-config-common
      NEO4J_server_default__advertised__address: primary3
      NEO4J_server_discovery_advertised__address: primary3:5000
      NEO4J_server_cluster_advertised__address: primary3:6000
      NEO4J_server_cluster_raft_advertised__address: primary3:7000
    networks:
      - lan
    volumes:
      - "./seeds:/seeds"