version: '3.7'
services:
    clustera-core1:
        hostname: clustera-core1
        image: neo4j:${NEO4J_VERSION}
        environment:
            - NEO4J_dbms_mode=core
            - NEO4J_dbms_connector_bolt_advertised__address=localhost:17687
            - NEO4J_dbms_default__listen__address=0.0.0.0
            - NEO4J_dbms_default__advertised__address=clustera-core1
            - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
            - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3
            - NEO4J_causal__clustering_initial__discovery__members=clustera-core1:5000,clustera-core2:5000,clustera-core3:5000
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_AUTH=neo4j/password
            - NEO4J_dbms_memory_heap_max__size=256M
            - NEO4J_dbms_memory_off__heap_max__size=50M
        ports:
            - 17474:7474
            - 17473:7473
            - 17687:7687
        profiles:
          - clustera
          - all
    clustera-core2:
        hostname: clustera-core2
        image: neo4j:${NEO4J_VERSION}
        environment:
            - NEO4J_dbms_mode=core
            - NEO4J_dbms_connector_bolt_advertised__address=localhost:27687
            - NEO4J_dbms_default__listen__address=0.0.0.0
            - NEO4J_dbms_default__advertised__address=clustera-core2
            - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
            - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3
            - NEO4J_causal__clustering_initial__discovery__members=clustera-core1:5000,clustera-core2:5000,clustera-core3:5000
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_AUTH=neo4j/password
            - NEO4J_dbms_memory_heap_max__size=256M
            - NEO4J_dbms_memory_off__heap_max__size=50M
        ports:
            - 27474:7474
            - 27473:7473
            - 27687:7687
        profiles:
          - clustera
          - all
    clustera-core3:
        hostname: clustera-core3
        image: neo4j:${NEO4J_VERSION}
        environment:
            - NEO4J_dbms_mode=core
            - NEO4J_dbms_connector_bolt_advertised__address=localhost:37687
            - NEO4J_dbms_default__listen__address=0.0.0.0
            - NEO4J_dbms_default__advertised__address=clustera-core3
            - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
            - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3
            - NEO4J_causal__clustering_initial__discovery__members=clustera-core1:5000,clustera-core2:5000,clustera-core3:5000
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_AUTH=neo4j/password
            - NEO4J_dbms_memory_heap_max__size=256M
            - NEO4J_dbms_memory_off__heap_max__size=50M
        ports:
            - 37474:7474
            - 37473:7473
            - 37687:7687
        profiles:
          - clustera
          - all
    clusterb-core1:
        hostname: clusterb-core1
        image: neo4j:${NEO4J_VERSION}
        environment:
            - NEO4J_dbms_mode=core
            - NEO4J_dbms_connector_bolt_advertised__address=localhost:18687
            - NEO4J_dbms_default__listen__address=0.0.0.0
            - NEO4J_dbms_default__advertised__address=clusterb-core1
            - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
            - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3
            - NEO4J_causal__clustering_initial__discovery__members=clusterb-core1:5005,clusterb-core2:5005,clusterb-core3:5005
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_AUTH=neo4j/password
            - NEO4J_dbms_memory_heap_max__size=256M
            - NEO4J_dbms_memory_off__heap_max__size=50M
            - NEO4J_causal__clustering_discovery__advertised__address=:5005
            - NEO4J_causal__clustering_discovery__listen__address=:5005
        ports:
            - 18474:7474
            - 18473:7473
            - 18687:7687
        profiles:
          - clusterb
          - all
    clusterb-core2:
        hostname: clusterb-core2
        image: neo4j:${NEO4J_VERSION}
        environment:
            - NEO4J_dbms_mode=core
            - NEO4J_dbms_connector_bolt_advertised__address=localhost:28687
            - NEO4J_dbms_default__listen__address=0.0.0.0
            - NEO4J_dbms_default__advertised__address=clusterb-core2
            - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
            - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3
            - NEO4J_causal__clustering_initial__discovery__members=clusterb-core1:5005,clusterb-core2:5005,clusterb-core3:5005
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_AUTH=neo4j/password
            - NEO4J_dbms_memory_heap_max__size=256M
            - NEO4J_dbms_memory_off__heap_max__size=50M
            - NEO4J_causal__clustering_discovery__advertised__address=:5005
            - NEO4J_causal__clustering_discovery__listen__address=:5005
        ports:
            - 28474:7474
            - 28473:7473
            - 28687:7687
        profiles:
          - clusterb
          - all
    clusterb-core3:
        hostname: clusterb-core3
        image: neo4j:${NEO4J_VERSION}
        environment:
            - NEO4J_dbms_mode=core
            - NEO4J_dbms_connector_bolt_advertised__address=localhost:38687
            - NEO4J_dbms_default__listen__address=0.0.0.0
            - NEO4J_dbms_default__advertised__address=clusterb-core3
            - NEO4J_causal__clustering_minimum__core__cluster__size__at__formation=3
            - NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime=3
            - NEO4J_causal__clustering_initial__discovery__members=clusterb-core1:5005,clusterb-core2:5005,clusterb-core3:5005
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_AUTH=neo4j/password
            - NEO4J_dbms_memory_heap_max__size=256M
            - NEO4J_dbms_memory_off__heap_max__size=50M
            - NEO4J_causal__clustering_discovery__advertised__address=:5005
            - NEO4J_causal__clustering_discovery__listen__address=:5005
        ports:
            - 38474:7474
            - 38473:7473
            - 38687:7687
        profiles:
          - clusterb
          - all
    fabric:
        hostname: matrix
        image: neo4j:${NEO4J_VERSION}
        environment:
            - NEO4J_dbms_mode=SINGLE
            - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
            - NEO4J_dbms_default__listen__address=0.0.0.0
            - NEO4J_dbms_default__advertised__address=matrix
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_AUTH=neo4j/password
            - NEO4J_dbms_memory_heap_max__size=256M
            - NEO4J_dbms_memory_off__heap_max__size=50M
            - NEO4J_fabric_database_name=matrix
            - NEO4J_fabric_routing_servers=clustera-core1:7687,clusterb-core1:7687
            - NEO4J_fabric_graph_0_name=blue
            - NEO4J_fabric_graph_0_uri=bolt://clustera-core1:7687,bolt://clustera-core2:7687,bolt://clustera-core3:7687
            - NEO4J_fabric_graph_0_database=blue
            - NEO4J_fabric_graph_1_name=red
            - NEO4J_fabric_graph_1_uri=bolt://clusterb-core1:7687,bolt://clusterb-core2:7687,bolt://clusterb-core3:7687
            - NEO4J_fabric_graph_1_database=red
        ports:
            - 7474:7474
            - 7473:7473
            - 7687:7687
        profiles:
          - fabric
          - all
