# Neo4j Single Core Scrape Config
scrape_configs:
  - job_name: 'neo4j-single'
    scrape_interval: '5s'
    static_configs:
      - targets: ['neo4j:2004']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(neo4j_database)_([a-zA-z0-9_]+)_((ids|check|cypher|db|pool|store|transaction)_[a-z_]+)'
        replacement: '${2}'
        target_label: database
        action: replace
      - source_labels: [__name__]
        regex: '(neo4j_database)_([a-zA-z0-9_]+)_((ids|check|cypher|db|pool|store|transaction)_[a-z_]+)'
        replacement: 'neo4j_database_$3'
        target_label: __name__
        action: replace